// pgs-ids.js — Play Games Services ID map (mobile / Android only).
//
// GENERATED by scripts/gen-pgs-ids.py from a Play Console "Get resources" export
// (store/pgs-import/games-ids.xml). To refresh after adding/renaming entries in
// the console, re-export and re-run:  python scripts/gen-pgs-ids.py
//
// Keys are the game's permanent internal names (they match steam.js's unlock()
// calls and board helpers); values are the opaque PGS ids. An empty value means
// that entry silently no-ops on mobile.

// ── Achievements: internal API name -> PGS achievement ID ────────────────────
export const PGS_ACHIEVEMENTS = {
  ACH_FIRST_DELIVERY: 'CgkIi6SZ6L8SEAIQEA',
  ACH_SAUCE_SLINGER:  'CgkIi6SZ6L8SEAIQAQ',
  ACH_HAMMER_CHEF:    'CgkIi6SZ6L8SEAIQEQ',
  ACH_WARLORD:        'CgkIi6SZ6L8SEAIQBg',
  ACH_TRIPLE_THREAT:  'CgkIi6SZ6L8SEAIQDQ',
  ACH_WIN_NORMAL:     'CgkIi6SZ6L8SEAIQGw',
  ACH_WIN_HARD:       'CgkIi6SZ6L8SEAIQCA',
  ACH_WIN_EXTREME:    'CgkIi6SZ6L8SEAIQCg',
  ACH_LEVEL_50:       'CgkIi6SZ6L8SEAIQFA',
  ACH_LEVEL_150:      'CgkIi6SZ6L8SEAIQAw',
  ACH_LEVEL_300:      'CgkIi6SZ6L8SEAIQBQ',
  ACH_FULL_LOADOUT:   'CgkIi6SZ6L8SEAIQCQ',
  ACH_MAX_WEAPON:     'CgkIi6SZ6L8SEAIQDg',
  ACH_GOLD_2500:      'CgkIi6SZ6L8SEAIQGA',
  ACH_RUSH_HOUR:      'CgkIi6SZ6L8SEAIQFw',
  ACH_KILLS_100000:   'CgkIi6SZ6L8SEAIQFQ',
  ACH_CHESTS_250:     'CgkIi6SZ6L8SEAIQGg',
  ACH_CLEAR_PINES:    'CgkIi6SZ6L8SEAIQDA',
  ACH_CLEAR_SLOPES:   'CgkIi6SZ6L8SEAIQGQ',
  ACH_CLEAR_GLACIER:  'CgkIi6SZ6L8SEAIQDw',
  ACH_NEW_HIRE:       'CgkIi6SZ6L8SEAIQCw',
  ACH_FULL_ROSTER:    'CgkIi6SZ6L8SEAIQAg',
  ACH_SIGNATURE:      'CgkIi6SZ6L8SEAIQEw',
  ACH_SLICE_BARON:    'CgkIi6SZ6L8SEAIQEg',
  ACH_OVERACHIEVER:   'CgkIi6SZ6L8SEAIQBw',
  ACH_UNTOUCHABLE:    'CgkIi6SZ6L8SEAIQFg',
  ACH_SPEED_DEMON:    'CgkIi6SZ6L8SEAIQBA',
};

// ── Leaderboards: internal board name -> PGS leaderboard ID ──────────────────
// Matrix boards mirror Steam (LB_<TYPE>_<ARENA>_<DIFF>); the single weekly board
// uses PGS's built-in WEEKLY time span (the dated weekly board name collapses to
// LB_WEEKLY_KILLS in pgsBoardId below).
export const PGS_LEADERBOARDS = {
  LB_ENDLESS_PINES_EASY:      'CgkIi6SZ6L8SEAIQHA',
  LB_ENDLESS_PINES_NORMAL:    'CgkIi6SZ6L8SEAIQHQ',
  LB_ENDLESS_PINES_HARD:      'CgkIi6SZ6L8SEAIQHg',
  LB_ENDLESS_PINES_EXTREME:   'CgkIi6SZ6L8SEAIQHw',
  LB_ENDLESS_SLOPES_EASY:     'CgkIi6SZ6L8SEAIQIA',
  LB_ENDLESS_SLOPES_NORMAL:   'CgkIi6SZ6L8SEAIQIQ',
  LB_ENDLESS_SLOPES_HARD:     'CgkIi6SZ6L8SEAIQIg',
  LB_ENDLESS_SLOPES_EXTREME:  'CgkIi6SZ6L8SEAIQIw',
  LB_ENDLESS_GLACIER_EASY:    'CgkIi6SZ6L8SEAIQJA',
  LB_ENDLESS_GLACIER_NORMAL:  'CgkIi6SZ6L8SEAIQJQ',
  LB_ENDLESS_GLACIER_HARD:    'CgkIi6SZ6L8SEAIQJg',
  LB_ENDLESS_GLACIER_EXTREME: 'CgkIi6SZ6L8SEAIQJw',
  LB_FASTWIN_PINES_EASY:      'CgkIi6SZ6L8SEAIQKA',
  LB_FASTWIN_PINES_NORMAL:    'CgkIi6SZ6L8SEAIQKQ',
  LB_FASTWIN_PINES_HARD:      'CgkIi6SZ6L8SEAIQKg',
  LB_FASTWIN_PINES_EXTREME:   'CgkIi6SZ6L8SEAIQKw',
  LB_FASTWIN_SLOPES_EASY:     'CgkIi6SZ6L8SEAIQLA',
  LB_FASTWIN_SLOPES_NORMAL:   'CgkIi6SZ6L8SEAIQLQ',
  LB_FASTWIN_SLOPES_HARD:     'CgkIi6SZ6L8SEAIQLg',
  LB_FASTWIN_SLOPES_EXTREME:  'CgkIi6SZ6L8SEAIQLw',
  LB_FASTWIN_GLACIER_EASY:    'CgkIi6SZ6L8SEAIQMA',
  LB_FASTWIN_GLACIER_NORMAL:  'CgkIi6SZ6L8SEAIQMQ',
  LB_FASTWIN_GLACIER_HARD:    'CgkIi6SZ6L8SEAIQMg',
  LB_FASTWIN_GLACIER_EXTREME: 'CgkIi6SZ6L8SEAIQMw',
  LB_LEVEL_PINES_EASY:        'CgkIi6SZ6L8SEAIQNA',
  LB_LEVEL_PINES_NORMAL:      'CgkIi6SZ6L8SEAIQNQ',
  LB_LEVEL_PINES_HARD:        'CgkIi6SZ6L8SEAIQNg',
  LB_LEVEL_PINES_EXTREME:     'CgkIi6SZ6L8SEAIQNw',
  LB_LEVEL_SLOPES_EASY:       'CgkIi6SZ6L8SEAIQOA',
  LB_LEVEL_SLOPES_NORMAL:     'CgkIi6SZ6L8SEAIQOQ',
  LB_LEVEL_SLOPES_HARD:       'CgkIi6SZ6L8SEAIQOg',
  LB_LEVEL_SLOPES_EXTREME:    'CgkIi6SZ6L8SEAIQOw',
  LB_LEVEL_GLACIER_EASY:      'CgkIi6SZ6L8SEAIQPA',
  LB_LEVEL_GLACIER_NORMAL:    'CgkIi6SZ6L8SEAIQPQ',
  LB_LEVEL_GLACIER_HARD:      'CgkIi6SZ6L8SEAIQPg',
  LB_LEVEL_GLACIER_EXTREME:   'CgkIi6SZ6L8SEAIQPw',
  LB_WEEKLY_KILLS:            'CgkIi6SZ6L8SEAIQQA',
};

// Resolve an achievement API name to its PGS id ('' if not present).
export function pgsAchId(api) { return PGS_ACHIEVEMENTS[api] || ''; }

// Resolve a board name to its PGS id. The dated weekly board
// (LB_WEEKLY_KILLS_<yyyymmdd>) collapses to the single LB_WEEKLY_KILLS entry.
export function pgsBoardId(board) {
  if (!board) return '';
  if (board.indexOf('LB_WEEKLY_KILLS') === 0) return PGS_LEADERBOARDS.LB_WEEKLY_KILLS || '';
  return PGS_LEADERBOARDS[board] || '';
}
