#!/usr/bin/env python3
"""
Assemble the Capacitor web-dir (www/) from the built web bundle.

Capacitor serves a single web-dir on-device. Our deployed artifact is:
    index.html            (generated by build-pages.py from src/wallop.html)
    src/js/*.js           (ES modules, imported with relative ./ paths)
    assets/**             (models, audio, ui, icons)

The relative paths in index.html (`src/js/main.js`, `assets/...`) only resolve
if www/ mirrors that layout, so we copy the three pieces into www/ verbatim.

Run AFTER build-pages.py (so index.html is current):
    python3 scripts/build-pages.py && python3 scripts/build-www.py
or via:  npm run build:cap

www/ is git-ignored — it's a build output, regenerated every sync.
"""

import os
import shutil

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
WWW  = os.path.join(ROOT, 'www')

INDEX = os.path.join(ROOT, 'index.html')


def main():
    if not os.path.exists(INDEX):
        raise SystemExit('index.html missing — run scripts/build-pages.py first')

    # Fresh www/ each time so deleted assets don't linger on-device.
    if os.path.isdir(WWW):
        shutil.rmtree(WWW)
    os.makedirs(WWW)

    # index.html at the web-dir root
    shutil.copy2(INDEX, os.path.join(WWW, 'index.html'))

    # src/ (the JS modules + inline splash author file) and assets/, mirrored
    # so the relative paths in index.html resolve unchanged in the WebView.
    shutil.copytree(os.path.join(ROOT, 'src'),    os.path.join(WWW, 'src'))
    shutil.copytree(os.path.join(ROOT, 'assets'), os.path.join(WWW, 'assets'),
                    # The raw Xelu prompt pack is source-only — we bundle just the
                    # extracted glyphs in assets/ui/glyphs/, not the 7.7MB pack.
                    ignore=shutil.ignore_patterns('Xelu_Free_Controller*'))

    # Rough size report so we notice if the bundle balloons.
    total = 0
    for dirpath, _dirs, files in os.walk(WWW):
        for f in files:
            total += os.path.getsize(os.path.join(dirpath, f))
    print(f'Assembled www/ ({total / (1024*1024):.1f} MB) — index.html + src/ + assets/')


if __name__ == '__main__':
    main()
