#!/usr/bin/env python3
# Fills src/js/pgs-ids.js from a Play Console "Get resources" export.
#
#   python scripts/gen-pgs-ids.py [path-to-games-ids.xml]
#   (default: store/pgs-import/games-ids.xml)
#
# Parses each <!--achievement/leaderboard <Display Name>--> + <string> pair and
# maps the Display Name to the game's internal key (ACH_* / LB_*), guaranteeing
# the exact opaque IDs land in the code without hand-transcription.

import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
XML = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'store', 'pgs-import', 'games-ids.xml')
OUT = os.path.join(ROOT, 'src', 'js', 'pgs-ids.js')

# Achievement display name -> internal key (mirrors scripts/gen-pgs-import.py).
ACH = {
    'First Delivery': 'ACH_FIRST_DELIVERY', 'Saucy': 'ACH_SAUCE_SLINGER',
    'Tenderized': 'ACH_HAMMER_CHEF', 'Employee of the Month': 'ACH_WARLORD',
    'Triple Threat': 'ACH_TRIPLE_THREAT', 'Well Done': 'ACH_WIN_NORMAL',
    'Extra Crispy': 'ACH_WIN_HARD', 'Burnt to a Crisp': 'ACH_WIN_EXTREME',
    'Getting Warmed Up': 'ACH_LEVEL_50', 'Fully Stacked': 'ACH_LEVEL_150',
    'Overcooked': 'ACH_LEVEL_300', 'The Works': 'ACH_FULL_LOADOUT',
    'Perfected Recipe': 'ACH_MAX_WEAPON', 'Big Tipper': 'ACH_GOLD_2500',
    'Rush Hour': 'ACH_RUSH_HOUR', 'Meat Grinder': 'ACH_KILLS_100000',
    'Treasure Hunter': 'ACH_CHESTS_250', 'Pines Patrol': 'ACH_CLEAR_PINES',
    'Slope Style': 'ACH_CLEAR_SLOPES', 'Cold Cuts': 'ACH_CLEAR_GLACIER',
    'New Hire': 'ACH_NEW_HIRE', 'Full Roster': 'ACH_FULL_ROSTER',
    'Signature Dish': 'ACH_SIGNATURE', 'Slice Baron': 'ACH_SLICE_BARON',
    'Overachiever': 'ACH_OVERACHIEVER', 'Untouchable': 'ACH_UNTOUCHABLE',
    'Speed Demon': 'ACH_SPEED_DEMON',
}

# Leaderboard display name -> internal key (generated from the matrix + weekly).
ARENAS = [('Pepperoni Pines', 'PINES'), ('Sundried Slopes', 'SLOPES'), ('Frostbite Glacier', 'GLACIER')]
DIFFS = [('Easy', 'EASY'), ('Normal', 'NORMAL'), ('Hard', 'HARD'), ('Extreme', 'EXTREME')]
TYPES = [('Endless', 'ENDLESS'), ('Fastest Win', 'FASTWIN'), ('Highest Level', 'LEVEL')]
LB = {}
for tname, tcode in TYPES:
    for aname, acode in ARENAS:
        for dname, dcode in DIFFS:
            LB[f'{tname} — {aname} ({dname})'] = f'LB_{tcode}_{acode}_{dcode}'
LB['Weekly Kills'] = 'LB_WEEKLY_KILLS'

# Ordered internal keys (so the generated file stays in a stable, readable order).
ACH_ORDER = list(ACH.values())
LB_ORDER = [f'LB_{tc}_{ac}_{dc}' for tc in ['ENDLESS','FASTWIN','LEVEL']
            for ac in ['PINES','SLOPES','GLACIER'] for dc in ['EASY','NORMAL','HARD','EXTREME']] + ['LB_WEEKLY_KILLS']

def parse(xml_text):
    pairs = re.findall(
        r'<!--\s*(achievement|leaderboard)\s+(.+?)\s*-->\s*<string[^>]*>([^<]+)</string>',
        xml_text)
    ach_ids, lb_ids = {}, {}
    for kind, display, gid in pairs:
        display = display.strip()
        gid = gid.strip()
        if kind == 'achievement':
            key = ACH.get(display)
            if not key: raise SystemExit(f'unmapped achievement: "{display}"')
            ach_ids[key] = gid
        else:
            key = LB.get(display)
            if not key: raise SystemExit(f'unmapped leaderboard: "{display}"')
            lb_ids[key] = gid
    return ach_ids, lb_ids

def main():
    with open(XML, encoding='utf-8') as f:
        ach_ids, lb_ids = parse(f.read())
    missing_a = [k for k in ACH_ORDER if k not in ach_ids]
    missing_l = [k for k in LB_ORDER if k not in lb_ids]
    if missing_a or missing_l:
        raise SystemExit(f'missing ids — achievements: {missing_a} leaderboards: {missing_l}')

    def ach_row(k): return f"  {(k + ':'):<20}'{ach_ids[k]}',"
    def lb_row(k):  return f"  {(k + ':'):<28}'{lb_ids[k]}',"

    ach_block = '\n'.join(ach_row(k) for k in ACH_ORDER)
    lb_block = '\n'.join(lb_row(k) for k in LB_ORDER)

    content = f'''// pgs-ids.js — Play Games Services ID map (mobile / Android only).
//
// GENERATED by scripts/gen-pgs-ids.py from a Play Console "Get resources" export
// (store/pgs-import/games-ids.xml). To refresh after adding/renaming entries in
// the console, re-export and re-run:  python scripts/gen-pgs-ids.py
//
// Keys are the game's permanent internal names (they match steam.js's unlock()
// calls and board helpers); values are the opaque PGS ids. An empty value means
// that entry silently no-ops on mobile.

// ── Achievements: internal API name -> PGS achievement ID ────────────────────
export const PGS_ACHIEVEMENTS = {{
{ach_block}
}};

// ── Leaderboards: internal board name -> PGS leaderboard ID ──────────────────
// Matrix boards mirror Steam (LB_<TYPE>_<ARENA>_<DIFF>); the single weekly board
// uses PGS's built-in WEEKLY time span (the dated weekly board name collapses to
// LB_WEEKLY_KILLS in pgsBoardId below).
export const PGS_LEADERBOARDS = {{
{lb_block}
}};

// Resolve an achievement API name to its PGS id ('' if not present).
export function pgsAchId(api) {{ return PGS_ACHIEVEMENTS[api] || ''; }}

// Resolve a board name to its PGS id. The dated weekly board
// (LB_WEEKLY_KILLS_<yyyymmdd>) collapses to the single LB_WEEKLY_KILLS entry.
export function pgsBoardId(board) {{
  if (!board) return '';
  if (board.indexOf('LB_WEEKLY_KILLS') === 0) return PGS_LEADERBOARDS.LB_WEEKLY_KILLS || '';
  return PGS_LEADERBOARDS[board] || '';
}}
'''
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(content)
    print(f'Wrote {os.path.relpath(OUT, ROOT)} — {len(ach_ids)} achievements + {len(lb_ids)} leaderboards')

if __name__ == '__main__':
    main()
